add online boutique images
kubesphere/image-sync-config pull request #6
Opened 2021-05-20 06:16 UTC by zackzhangkai

Signed-off-by: zackzhangkai <zhangkaiamm@gmail.com>

2021-05-20 06:16 UTC, zackzhangkai commented
/assign @zryfish

2021-05-25 09:58 UTC, zackzhangkai commented
@zryfish please merge it.

2021-05-30 05:35 UTC, LinuxSuRen commented on rules/aliyun/service.yaml
> +"gcr.io/google-samples/microservices-demo/frontend:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/frontend:v0.2.3"
I'd suggest that using an alternative image repo name. For example, `frontend` is a generic name. It's possible to conflict with others.

Secondly, all those images belong to a group. It's good to group them.

Suggestion mapping: `gcr.io/google-samples/microservices-demo/frontend:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/microservices-demo/frontend:v0.2.3`.

2021-06-01 06:35 UTC, zackzhangkai commented on rules/aliyun/service.yaml
> +"gcr.io/google-samples/microservices-demo/frontend:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/frontend:v0.2.3"
done

2021-06-01 06:38 UTC, LinuxSuRen approved these changes
/lgtm

2021-06-01 07:06 UTC, zryfish requested changes

2021-06-01 07:06 UTC, zryfish commented on rules/aliyun/service.yaml
> +"gcr.io/google-samples/microservices-demo/adservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/microservices-demo/adservice:v0.2.3"
the destination address is incorrect, `kubesphereio` is the organization name,  right after org is the repository name, `microservices-demo` is unnecessary and incorrect.

2021-06-01 13:23 UTC, zackzhangkai commented on rules/aliyun/service.yaml
> +"gcr.io/google-samples/microservices-demo/adservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/microservices-demo/adservice:v0.2.3"
@LinuxSuRen Any suggestions?

2021-06-01 13:34 UTC, LinuxSuRen commented on rules/aliyun/service.yaml
> +"gcr.io/google-samples/microservices-demo/adservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/microservices-demo/adservice:v0.2.3"
It worked before. But we cannot do it anymore. Please see the following notice:

![image](https://user-images.githubusercontent.com/1450685/120331733-ab957280-c320-11eb-9047-8f43169e6a76.png)

In my opinion, we should put the images which come from KubeSphere into the namespace `registry.cn-beijing.aliyuncs.com/kubesphereio`. So how about creating a new namespace, for example: `registry.cn-beijing.aliyuncs.com/kubespheredemo`?

But I don't block it due to my suggestion might cause extra cost.

2021-06-02 02:27 UTC, LinuxSuRen approved these changes
/lgtm

2021-06-02 03:44 UTC, zryfish commented on rules/aliyun/service.yaml
> +"gcr.io/google-samples/microservices-demo/adservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/microservices-demo/adservice:v0.2.3"
we are using a free trier account on Aliyun CR, and are limited to only 2 namespaces, can't afford to create another one, since there are already `kubesphereio` and `openpitrix`. So just sync to kubesphereio currently.

2021-06-02 03:45 UTC, merged